/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PemaAmbulanceWlList {
    }
}
declare global {
    interface HTMLPemaAmbulanceWlListElement extends Components.PemaAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLPemaAmbulanceWlListElement: {
        prototype: HTMLPemaAmbulanceWlListElement;
        new (): HTMLPemaAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "pema-ambulance-wl-list": HTMLPemaAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface PemaAmbulanceWlList {
    }
    interface IntrinsicElements {
        "pema-ambulance-wl-list": PemaAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pema-ambulance-wl-list": LocalJSX.PemaAmbulanceWlList & JSXBase.HTMLAttributes<HTMLPemaAmbulanceWlListElement>;
        }
    }
}
